apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: crypto-price-render
  name: crypto-price-render
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: crypto-price-render
