version: '3.8'
services:
  crypto-price-render:
    ports:
      - "80:3000"
    cpu_count: 1
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:3000/api/ || exit 1
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 30s
